language: node_js
node_js:
  - 0.10
branches:
  only:
    - gh-pages
    - master
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g karma bower
  - bower install
script:
  - karma start karma.conf.js --log-level=disable --single-run --browsers=Firefox --reporters=dots
